### ISSUE TITLE
AIX version fails assertion in fs watch related test cases

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#16]
Three test cases fail with the exceptions:

test-fs-readfile-error.js
AssertionError: null == true
    at /home/gireesh/aix/node.nnew/node/test/simple/test-fs-readfile-error.js:34:5
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

test-fs-readfile-pipe.js:

AssertionError: it exits normally
    at /home/gireesh/aix/node.nnew/node/test/simple/test-fs-readfile-pipe.js:51:3
    at ChildProcess.exithandler (child_process.js:641:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:735:16)
    at Socket.<anonymous> (child_process.js:948:11)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)

test-fs-watch.js:

Error: watch ENOSYS
    at errnoException (fs.js:1019:11)
    at FSWatcher.start (fs.js:1051:11)
    at Object.fs.watch (fs.js:1076:11)
    at assert.doesNotThrow.fs.watch.renameEv (/home/gireesh/aix/node.nnew/node/test/simple/test-fs-watch.js:65:24)
    at Function._throws (assert.js:290:5)
    at Function.assert.doesNotThrow (assert.js:321:11)
    at Object.<anonymous> (/home/gireesh/aix/node.nnew/node/test/simple/test-fs-watch.js:63:8)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
On the face of it, the issues are due the lack of file system watch facility in AIX.

**Comment by gireeshpunathil** [comment]
Basic fs support is in place through AHAFS based solution. Closing this issue
