### ISSUE TITLE
AIX version fails with assertion: unexpected response received from server.

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#18]
The test case fail with the exception:

bash-4.2$ ./node test/simple/test-http-upgrade-server.js

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: "HTTP/1.1 200" == "0\r\n\r\n"
    at Socket.<anonymous> (/home/gireesh/aix/node/test/simple/test-http-upgrade-server.js:160:12)
    at Socket.EventEmitter.emit (events.js:95:17)
    at Socket.<anonymous> (_stream_readable.js:746:14)
    at Socket.EventEmitter.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:408:10)
    at emitReadable (_stream_readable.js:404:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:526:21)

Recreatable using a simple http server with a client receiving a 'hello' message.

**Comment by gireeshpunathil** [comment]
Closing this issue as this is no more a concern. Will re-open if this issue surfaces again.
