### ISSUE TITLE
AIX version fails with timeout in automated live debugging scenario

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#20]
The test test/simple/test-debugger-repl-break-in-module.js fails with the below exception

dying badly buffer="debug> debug> "
child is closed
UncaughtException [Error: Timeout. Expected: /break in .*[\\\/]main\.js:4/] Error: Timeout. Expected: /break in .*[\\\/]main\.js:4/
    at ChildProcess.<anonymous> (/home/gireesh/aix/node/test/simple/helper-debugger-repl.js:89:13)
    at ChildProcess.EventEmitter.emit (events.js:117:20)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
Error: Timeout. Expected: /break in .*[\\\/]main\.js:4/
process exit 1

**Comment by gireeshpunathil** [comment]
Issue resolved through a change in the test case through https://github.com/nodejs/node/commit/e12e72eb58c68b82f5bbd89e094cf7fb7b7e00c8
