### ISSUE TITLE
AIX version fails with assertion on zombie cluster workers after master dies

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#21]
Two test cases fail with similar errors:

test-cluster-master-error.js

bash-4.2$ ./node test/simple/test-cluster-master-error.js

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: The workers did not die after an error in the master
    at process.<anonymous> (/home/gireesh/aix/node/test/simple/test-cluster-master-error.js:137:12)
    at process.g (events.js:180:16)
    at process.EventEmitter.emit (events.js:117:20)

test-cluster-master-kill.js:

bash-4.2$ ./node test/simple/test-cluster-master-kill.js

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: worker was alive after master died
    at process.<anonymous> (/home/gireesh/aix/node/test/simple/test-cluster-master-kill.js:95:12)
    at process.g (events.js:180:16)
    at process.EventEmitter.emit (events.js:117:20)

**Comment by gireeshpunathil** [comment]
Issue resolved through a change in the test case: https://github.com/nodejs/node/pull/2891
