### ISSUE TITLE
AIX version fails due to many http requests being timed out.

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#22]
Simple test test/simple/test-http-client-timeout-agent.js fails with this call stack:

assert.js:92
  throw new assert.AssertionError({
        ^
AssertionError: timeout on http request called too much
    at process.<anonymous> (/home/gireesh/aix/node/test/simple/test-http-client-timeout-agent.js:95:10)
    at process.EventEmitter.emit (events.js:117:20)

**Comment by gireeshpunathil** [comment]
Closing this issue now as this does not seem to be happening now. If this is found to be a problem, will re-open
