### ISSUE TITLE
process._debugProcess kills the V8 debugger

### ISSUE THREAD

**Issue by gireeshpunathil** [andrewlow/node#23]
AIX version fails with ECONNRESET or EPIPE or ECONNREFUSED
Simple test test/simple/test-debugger-client.js fails with one of the following stack:
_____________________________________________________
got stderr data "debugger listening on port 13683\n"
>>> new node process: 12189734
>>> starting debugger session
>>> connecting...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
_____________________________________________________
>>> new node process: 13566188
>>> starting debugger session
got stderr data "debugger listening on port 13683\n"
>>> connecting...

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

_____________________________________________________
got stderr data "debugger listening on port 13683\n"
>>> connecting...
>>> new node process: 12189732
>>> starting debugger session
ready!
requesting version

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)

**Comment by gireeshpunathil** [comment]
Issue is resolved, closing.
